project_id = "pudfybkyfedeggmokhco"

[functions.check-duplicate-expense]
verify_jwt = true

[functions.check-unread-messages]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54329

[analytics]
enabled = false

[functions.process-withdrawal]
verify_jwt = true

[functions.check-withdrawal-status]
verify_jwt = true

[functions.test-function]
verify_jwt = true

[functions.test-sms]
verify_jwt = true

[functions.sms-login-link]
verify_jwt = true

[functions.detect-ip]
verify_jwt = true

[functions.check-network-access]
verify_jwt = true

[functions.calculate-metrics]
verify_jwt = true

[functions.send-password-reset-sms]
verify_jwt = true

[functions.generate-risk-assessment]
verify_jwt = true

[functions.generate-comparison-insights]
verify_jwt = true

[functions.fetch-ice-prices]
verify_jwt = false

[functions.analyst-report-reminder]
verify_jwt = false

[functions.daily-report-reminder]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.analyst-price-reminder]
verify_jwt = false

[functions.morning-report-reminder]
verify_jwt = false
